# Site settings
title: "Zack Urben"
description: The personal website for Zack Urben. A place where developers can REST and learn codefu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zackurben.com" # the base hostname & protocol for your site

# Social Info
email: "zackurben@gmail.com"
twitter_profile: "https://twitter.com/zackurben"
github_profile: "https://github.com/zackurben"
linkedin_profile: "https://www.linkedin.com/in/zackurben"

projects:
  - name: "EZEDIT"
    client: "General Public"
    project: "Platform As A Service (PAAS)"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
      - name: "Rahat Ahmed"
        link: "http://rahatah.me/d/"
    link:
      - label: "GitHub"
        link: "https://github.com/ezedit/ezedit"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "mongoDB"
        link: "http://www.mongodb.org/"
      - label: "Expressjs"
        link: "http://expressjs.com/"
      - label: "Backbone.js"
        link: "http://backbonejs.org/"
    about: "EZEDIT is a Platform as a Service (PAAS) for web designers to give their clients full control of the
            digital content on their website. As a designer, you make a website and tag HTML fields with
            data-attributes that you want the client to have access to edit; after mapping the corresponding
            fields on the service, the client can login to EZEDIT and manipulate the contents displayed on their site
            in realtime. On page load, the site generated js file will call the EZEDIT API and display the most recent
            content on the site. EZEDIT is an open source project under the MIT license."
  - name: "Language Processing for Education"
    client: "MemoryScience"
    project: "Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Spencer Fusco"
        link: "#"
      - name: "Scarlett Hunt"
        link: "#"
      - name: "Grant Cox"
        link: "#"
    link:
      - label: "Proprietary"
        link: "#"
    tech:
      - label: "PHP"
        link: "http://php.net/"
      - label: "Linux"
        link: "http://www.linux.com/"
      - label: "JSON"
        link: "http://json.org/"
      - label: "Stanford Parser"
        link: "http://nlp.stanford.edu/software/lex-parser.shtml"
    about: "This was a Capstone Project, created for MemoryScience, to automate their current manual workflow. This
            application takes an input body of text, of unlimited length, and converts it into the essential keywords
            using context free grammar modeling. These keywords are used in conjunction with the original content to aid
            in the process of information retention, using the MemoryScience LockIN program. My role in this project
            was, to lead my fellow peers to create a viable solution to solve the problem of manual information
            processing currently in-place at MemoryScience. I served as the lead developer and created a custom PHP
            wrapper for interacting with the core Stanford NLP library, which allowed us to get the desired output from
            the given input, ultimately allowing us to streamline the current workflow."

# Build settings
markdown: kramdown
