# Site settings
title: "Zack Urben"
description: The personal website for Zack Urben. A place where developers can REST and learn codefu.
baseurl: ""
url: "http://zackurben.com"
plugins: ["jekyll-paginate"]

bio: "
I am a Computer Scientist located in Dallas, Texas, and a Software Engineer at
Sony. I am interested in many things, but I focus on open source, web design,
security, and finance. I am <em><strong>passionate</strong></em> about
programming and creating elegant solutions that follow the UNIX Philosophy.
Curious in nature and dedicated to learning new things, I thrive on a web stack.
"

# Social Info
email: "zackurben@gmail.com"
twitter_profile: "https://twitter.com/zackurben"
github_profile: "https://github.com/zackurben"
linkedin_profile: "https://www.linkedin.com/in/zackurben"

projects:
  - name: "Knights Quest"
    client: "General Public"
    project: "Web Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
    link:
      - label: "GitHub"
        link: "https://github.com/zjlabs/js13kgames2020-submission"
      - label: "js13kgames"
        link: "https://js13kgames.com/entries/knights-quest"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "rollup"
        link: "https://rollupjs.org/guide/en/"
      - label: "socket.io"
        link: "https://socket.io/docs/"
    about: "Knights Quest is a game designed for <a href=\"https://js13kgames.com\">JS13kGames</a>. The final
            submission can be found <a href=\"https://js13kgames.com/entries/knights-quest\">here</a>.
            Knights Quest is a realtime online multiplayer game that allows players to engage in combat to
            reclaim their legendary gear! This game won 3rd in the Server category!
            The entire game source fits within 13k and is an open source project under the MIT license"
  - name: "Tube Masters"
    client: "General Public"
    project: "Web Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
    link:
      - label: "GitHub"
        link: "https://github.com/zackurben/js13k-2019"
      - label: "js13kgames"
        link: "http://js13kgames.com/entries/tube-masters"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "webpack"
        link: "https://webpack.js.org/"
      - label: "WebGL"
    about: "Tube Masters is a game designed for <a href=\"https://js13kgames.com\">JS13kGames</a>, and the final
            submission can be found <a href=\"http://js13kgames.com/entries/tube-masters\">here</a>.
            In Tube Masters, you play daredevil who is tubing down the side of a mountain.
            Pay attention and avoid the obstacles, while trying to get the highest score possible!
            The entire game source fits within 13k and is an open source project under the MIT license"
  - name: "NETWORK HELL"
    client: "General Public"
    project: "Web Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
    link:
      - label: "GitHub"
        link: "https://github.com/zackurben/js13k-2018"
      - label: "js13kgames"
        link: "https://js13kgames.com/entries/network-hell"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "webpack"
        link: "https://webpack.js.org/"
    about: "NETWORK HELL is a game designed for <a href=\"https://js13kgames.com\">JS13kGames</a>, and the final
            submission can be found <a href=\"https://js13kgames.com/entries/network-hell\">here</a>.
            In Network Hell, you play the role of a request traveling back up the
            [OSI Stack](https://en.wikipedia.org/wiki/OSI_model) to try and connect to the outside world.
            Move quickly and pickup packets along the way to provide data to your consumer with the least
            response time. The entire game source fits within 13k and is an open source project under the MIT license"
  - name: "AlphaVantage"
    client: "General Public"
    project: "NPM Module"
    team:
      - name: "Zack Urben"
        link: "#"
    link:
      - label: "GitHub"
        link: "https://github.com/zackurben/alphavantage"
      - label: "NPM"
        link: "https://www.npmjs.com/package/alphavantage"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
    about: "AlphaVantage is a free online resource for realtime and historical stock information. As an early
            adopter of the service, I created the first npm package. This is an extensive implementation of
            the service, including automated tests, which includes support for all of the API endpoints and a
            few utilities for data normalization. The npm module is an open source project under the MIT license"
  - name: "VacationRoulette"
    client: "General Public"
    project: "Web Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
      - name: "Rahat Ahmed"
        link: "http://rahatah.me/d/"
    link:
      - label: "GitHub"
        link: "https://github.com/vacationroulette/vacationroulette"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "Expressjs"
        link: "http://expressjs.com/"
      - label: "Pure CSS"
        link: "http://purecss.io/"
    about: "VacationRoulette is a web application that allows anyone to find a vacation quickly, without much planning.
            Utilizing the public API provided by <a href=\"https://developer.sabre.com/\">Sabre</a>, VacationRoulette
            can generate spur of the moment, round-trip, vacations without requiring you to plan the vacation yourself.
            Using the Sabre data and our optional filters, we create dynamic <a href=\"http://www.kayak.com/\">Kayak</a>
            URLs to book the trip using the provider of your choice. VacationRoulette requires only a leaving/returning
            date and an Airport code to get started. Additionally, you may use the optional filters such as: general
            price point, desired theme, and relative location. Once a suggestion has been made, you can book a trip
            using that information, or generate a new trip. VacationRoulette is an open source project under the MIT
            license, and was made for <a href=\"http://hackdfw.com/\">HackDFW</a>."
  - name: "zackurben.com"
    client: "General Public"
    project: "Website"
    team:
      - name: "Zack Urben"
        link: "#"
    link:
      - label: "GitHub"
        link: "https://github.com/zackurben/zackurben.github.io"
    tech:
      - label: "Jekyll"
        link: "http://jekyllrb.com/"
      - label: "Sass"
        link: "http://sass-lang.com/"
      - label: "jQuery"
        link: "http://jquery.com/"
      - label: "normalize.css"
        link: "http://necolas.github.io/normalize.css/"
      - label: "Chart.js"
        link: "http://www.chartjs.org/"
      - label: "Modernizr"
        link: "http://modernizr.com/"
    about: "My profile website is the test bed that enables me to learn new technology. For this website, I created just
           about everything, from the design to the custom grid. I wanted to make a static website where I could play
           curator for my living resume. I deployed Jekyll to create static pages, so I could harness both the power of
           its templating engine and blogging platform."
  - name: "EZEDIT"
    client: "General Public"
    project: "Platform As A Service (PAAS)"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Jon Darling"
        link: "http://jmdarling.com/"
      - name: "Rahat Ahmed"
        link: "http://rahatah.me/d/"
    link:
      - label: "GitHub"
        link: "https://github.com/ezedit/ezedit"
    tech:
      - label: "Node.js"
        link: "http://nodejs.org/"
      - label: "mongoDB"
        link: "http://www.mongodb.org/"
      - label: "Expressjs"
        link: "http://expressjs.com/"
      - label: "Backbone.js"
        link: "http://backbonejs.org/"
      - label: "Bootstrap"
        link: "http://getbootstrap.com/"
    about: "EZEDIT is a Platform as a Service (PAAS) for web designers to give their clients full control of the
            digital content on their website. As a designer, you make a website and tag HTML fields with
            data-attributes that you want the client to have access to edit; after mapping the corresponding
            fields on the service, the client can login to EZEDIT and manipulate the contents displayed on their site
            in realtime. On page load, the site generated js file will call the EZEDIT API and display the most recent
            content on the site. EZEDIT is an open source project under the MIT license, and was made for
            <a href=\"http://hackutd.co/\">Hack_UTD</a>."
  - name: "Language Processing for Education"
    client: "MemoryScience"
    project: "Application"
    team:
      - name: "Zack Urben"
        link: "#"
      - name: "Spencer Fusco"
        link: "www.linkedin.com/pub/spencer-fusco/aa/832/89b/en"
      - name: "Scarlett Hunt"
        link: "https://www.linkedin.com/pub/kendall-hunt/66/843/a22"
      - name: "Grant Cox"
        link: "#"
    link:
      - label: "Proprietary"
        link: "#"
    tech:
      - label: "PHP"
        link: "http://php.net/"
      - label: "Linux"
        link: "http://www.linux.com/"
      - label: "JSON"
        link: "http://json.org/"
      - label: "Stanford Parser"
        link: "http://nlp.stanford.edu/software/lex-parser.shtml"
    about: "This was a Capstone Project, created for MemoryScience, to automate their current manual workflow. This
            application takes an input body of text, of unlimited length, and converts it into the essential keywords
            using context free grammar modeling. These keywords are used in conjunction with the original content to aid
            in the process of information retention, using the MemoryScience LockIN program. My role in this project
            was, to lead my fellow peers to create a viable solution to solve the problem of manual information
            processing currently in-place at MemoryScience. I served as the lead developer and created a custom PHP
            wrapper for interacting with the core Stanford NLP library, which allowed us to get the desired output from
            the given input, ultimately allowing us to streamline the current workflow."
  - name: "CEX.IO Reinvestor"
    client: "General Public"
    project: "Application"
    team:
      - name: "Zack Urben"
        link: "#"
    link:
      - label: "GitHub"
        link: "https://github.com/zackurben/cex.io-reinvestor"
    tech:
      - label: "Java"
        link: "https://www.java.com/en/"
      - label: "Google GSON"
        link: "https://code.google.com/p/google-gson/"
    about: "This was a personal project, created to automate the process of reinvesting my dividend earnings back into
            the Bitcoin Exchange CEX.IO. First created using PHP and my contributions to the API library, I ported the
            project to Java and created the Java API Library. I made this in Java so others could use it, without
            compiling PHP with pthreads, since Java ships natively with multithreading support. This is an open source
            project under the MIT license."

permalink: /blog/:title/
defaults:
  -
    scope:
      type: "posts"
      path: "blog"
    values:
      layout: "post"

paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
