# Site settings
title: "Zack Urben"
description: The personal website for Zack Urben. A place where developers can REST and learn codefu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zackurben.com" # the base hostname & protocol for your site

# Social Info
email: "zackurben@gmail.com"
twitter_profile: "https://twitter.com/zackurben"
github_profile: "https://github.com/zackurben"
linkedin_profile: "https://www.linkedin.com/in/zackurben"

# Build settings
markdown: kramdown
